### ISSUE TITLE
Running "Launch Emulator" gives "ReferenceError: primordials is not defined"

### ISSUE THREAD

**Issue by hornta** [OfficeDev/microsoft-teams-sample-complete-node#74]
Just cloned this repo, ran npm i and tried to launch emulator with this output:
```
> Executing task: npm run -s build <

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\hornta\Documents\GitHub\tjelvar\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\hornta\Documents\GitHub\tjelvar\node_modules\natives\index.js:55:10)      
    at Object.<anonymous> (C:\Users\hornta\Documents\GitHub\tjelvar\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
The terminal process terminated with exit code: 1
```

**Comment by hornta** [comment]
Seems to work with node 11. I was running node 12
